name: Build and Push API Dev Image
on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Login to Grava Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.EXTERNAL_PRIVATE_REGISTRY }}
          username: ${{ secrets.EXTERNAL_PRIVATE_REGISTRY_USERNAME }}
          password: ${{ secrets.EXTERNAL_PRIVATE_REGISTRY_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          file: Dockerfile
          tags: ${{ secrets.EXTERNAL_PRIVATE_REGISTRY }}/telescope/api:${{ github.ref_name }}